title: Michalis Moutselos
description: TODO

url: http://kongeor.github.com/michalis
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   facebook: michalis.moutselos
   email: moutselos@gmail.com

google_analytics: ""
